# Render Blueprint para WADE COLETOR
# Configuração otimizada e robusta

services:
  - type: web
    name: wade-coletor
    env: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --access-logfile - --error-logfile -"
    plan: free
    healthCheckPath: "/"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.4